### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by lorenzoprivakun** [motebaya/tiktok-js#1]
HELLO SECRET_KEY WHAT IS IT FOR? I ASK YOU, BECAUSE WHEN I RUN IT, THE ERROR IN SECRET_KEY

**Comment by motebaya** [comment]
> HELLO SECRET_KEY WHAT IS IT FOR? I ASK YOU, BECAUSE WHEN I RUN IT, THE ERROR IN SECRET_KEY

kindly read in section, [Setup Web Server](https://github.com/motebaya/tiktok-js#setup-web-server).
i've write it, make sure you've rename [.env-example](https://github.com/motebaya/tiktok-js/blob/main/.env-example) to `.env`.
